[package]
name = "rpsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
regex = "1"
serde_json = "1.0"
sha256 = "1.1.1"
thiserror = "1"
